### ISSUE TITLE
Create reviewer page. View all assigned files and be able to sort them based on when they're due.

### ISSUE THREAD

**Issue by acournoyer1** [DanGravel/SYSC4806#1]

**Comment by acournoyer1** [comment]
Blocked by Liam's article not having a date.

**Comment by liamhickey** [comment]
The date is just a field/getter that is included in master, work off of that. You are not blocked.

**Comment by acournoyer1** [comment]
I've been working off your article code, are you gonna change everything to use the file in master or keep that? I can change up your article code to keep it instead.
