### ISSUE TITLE
Upload page, make all of file upload clickable

### ISSUE THREAD

**Issue by DanGravel** [DanGravel/SYSC4806#91]
You can currently click the select file to upload, when clicked it should open file selection

**Comment by br0wncrust4cean** [comment]
Is this really a necessary fix? They could just click the browse button that's right there. That it's purpose lol.

**Comment by DanGravel** [comment]
> Is this really a necessary fix? They could just click the browse button that's right there. That it's purpose lol.

More of a usability thing, not a huge issue but either make it non selectable or do something when its selcted

**Comment by DanGravel** [comment]
As per Taz's comment maybe use the bootstrap file uploader
